/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blacklist: typeof import('./src/components/manage/blacklist.vue')['default']
    Btn: typeof import('./src/components/results-display/btn.vue')['default']
    Keywords: typeof import('./src/components/manage/keywords.vue')['default']
    Manage: typeof import('./src/components/manage/manage.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ResultsDisplay: typeof import('./src/components/results-display/results-display.vue')['default']
    UpdateData: typeof import('./src/components/manage/update-data.vue')['default']
    WhiteList: typeof import('./src/components/manage/white-list.vue')['default']
  }
}
